services:
  redis:
    image: redis:latest
    networks:
      - net
    restart: unless-stopped

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - net
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  app:
    hostname: mydocker
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: app   # name image created at build
    ports:
      - 8080:${PORT}
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - FILE_PATH_TO_CHECK=${FILE_PATH_TO_CHECK}
    volumes:
      - ./dummy.txt:/app/dummy.txt
      - ./index.ts:/app/index.ts
    networks:
      - net
    restart: unless-stopped
    depends_on:
      - redis
      - mysql

networks:
  net:
    driver: bridge

volumes:
  db:
