services:
    dummy-cache:
        image: redis:latest
        environment:
            REDIS_PORT: 6379
        networks:
            - dummy-net

    dummy-db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'tH1sIsThEr0oTp@sSW0rD'
            MYSQL_DATABASE: my_database
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        networks:
            - dummy-net
        volumes:
            - dummy-vol-db:/var/lib/mysql

    dummy-app:
        depends_on:
            - dummy-cache
            - dummy-db
        hostname: mydocker
        user: 1:1
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            PORT: 1337
            REDIS_HOST: dummy-cache
            REDIS_PORT: 6379
            MYSQL_HOST: dummy-db
            MYSQL_PORT: 3306
            MYSQL_DB: my_database
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        ports:
            - 80:1337
        networks:
            - dummy-net

networks:
    dummy-net:
        driver: bridge

volumes:
    dummy-vol-db: